name: Build INDI Libs for Arch Linux ARM64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    # container:
    #   image: lopsided/archlinux:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
# 2. Uruchomienie budowania wewnątrz kontenera Arch Linux ARM64
      - name: Build Arch package inside container
        run: |
          docker run --rm \
            --privileged \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            lopsided/archlinux:latest /bin/bash -c "
            # Inicjalizacja pacmana i instalacja niezbędnych narzędzi
            pacman-key --init
            pacman-key --populate archlinux
            pacman -Syu --noconfirm --needed base-devel git sudo

            # Budowanie pakietu jako użytkownik nie-root (wymóg makepkg)
            useradd -m builder
            echo 'builder ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
            chown -R builder:builder .

            cp PKGBUILD.core PKGBUILD
            # Budowanie pakietu w domyślnej lokalizacji
            sudo -u builder makepkg -s --noconfirm

            echo '===================== After core build ==================='

            ls /workspace/
            sudo pacman -U /workspace/*.pkg.tar.*
            
            cp PKGBUILD.3rdparty-libs PKGBUILD
            # Budowanie pakietu w domyślnej lokalizacji
            sudo -u builder makepkg -s --noconfirm

            echo '===================== After libs build ==================='
            ls /workspace/
            sudo pacman -U /workspace/*.pkg.tar.*

            cp PKGBUILD.3rdparty-drivers PKGBUILD
            # Budowanie pakietu w domyślnej lokalizacji
            sudo -u builder makepkg -s --noconfirm

            echo '===================== After drivers build ==================='

            ls /workspace/
            sudo pacman -U /workspace/*.pkg.tar.*            
            
            # Przywrócenie uprawnień roota dla plików w workspace, aby host (GitHub Actions) 
            # mógł nimi zarządzać i sprzątać bez błędów 'Permission denied'
            chown -R root:root /workspace
          "
      - name: Upload compiled package
        uses: actions/upload-artifact@v4
        with:
          name: libindi-arch-arm64
          path: "*.pkg.tar.*"
          retention-days: 14
